repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-json
    -   id: check-case-conflict
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: mixed-line-ending
