[tool.roo]

[[tool.roo.source]]
name = "CRAN"
url = "https://cloud.r-project.org/"

[tool.roo.dependencies]
assertthat = "0.2.1"
R6 = "2.4.1"

[tool.roo.dev-dependencies]
testthat = "3.0.1"
lintr = "2.0.1"
devtools = "2.2.2"
tibble = "3.0.3"
here = "0.1"
covr = "3.5.1"

[tool.roo.doc-dependencies]
knitr = "1.28"
pkgdown = "1.5.1"
